### ISSUE TITLE
Does not work in Autopsy 4.17

### ISSUE THREAD

**Issue by normaliok** [labcif/TikTok#1]
There is no adb extraction in start window
![Screenshot 2020-12-25 115643](https://user-images.githubusercontent.com/35446022/103129826-38ba0880-46ab-11eb-9e80-5008354213f2.jpg)

**Comment by rubnogueira** [comment]
In order to use this feature, Autopsy requires this pull request which enable support for Jython Datasource Processor modules. https://github.com/sleuthkit/autopsy/pull/6027

You have to wait until sleuthkit merges it or you can compile Autopsy with those changes.

**Comment by rubnogueira** [comment]
This feature will be available in Autopsy 4.20.

**Comment by rubnogueira** [comment]
Supported with 4.20
https://www.autopsy.com/autopsy-4-20-0-is-finally-out-with-new-pipelines-and-fixes/
