### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by ArielEdAburto** [labcif/TikTok#3]
When I start autopsy 4.19.3, I get an error in FAMA module

![Screenshot_1](https://user-images.githubusercontent.com/108342570/195368014-cdf2cb2c-d853-4dc5-baa1-de43257c22d0.png)

I would appreciate any help!

![image](https://user-images.githubusercontent.com/108342570/195368273-cfc5feb7-2dc0-4911-b926-7a1e924615da.png)

**Comment by rubnogueira** [comment]
@ArielEdAburto thanks for your input. In order to add support for https://github.com/sleuthkit/autopsy/pull/6027 which should come with Autopsy 4.20, it got broken for <4.20 versions.

Can you check with the latest master version?

**Comment by ArielEdAburto** [comment]
Now it works!

It would be nice to be able to analyze the .db files generated by Magnet Acquire. Is there any possibility?
Since rooting a device to get the information is not an alternative.

**Comment by rubnogueira** [comment]
Thanks for the suggestion. We don't have plans for it right now.
